# - id: doi:10.2196/63220
#  type: paper
# description: Using a 3-arm randomized controlled trial, this study will examine the effectiveness of PC-SMILE in reducing depression and anxiety symptoms among children.
# date: 2024-06-13
# image:
# buttons:
#  - type: manubot
#     link: https://greenelab.github.io/meta-review/
#   - type: source
#     text: Manuscript Source
#      link: https://github.com/greenelab/meta-review
#    - type: website
#     link: http://manubot.org/
# tags:
#    - open science
#   - collaboration
# repo: greenelab/meta-review

